"""add isPromotional and value_promotional

Revision ID: 08bee7087579
Revises: a9d4b03c89c7
Create Date: 2026-03-20 14:32:11.036724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bee7087579'
down_revision = 'a9d4b03c89c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isPromotional', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price_promotional', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('price_promotional')
        batch_op.drop_column('isPromotional')

    # ### end Alembic commands ###
