"""remove unique in orders

Revision ID: 0f87e5b478ec
Revises: f320f23d2925
Create Date: 2025-11-23 23:35:16.448189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f87e5b478ec'
down_revision = 'f320f23d2925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_order_number_key'), type_='unique')
        batch_op.create_unique_constraint('uq_menu_order_number', ['menu_id', 'order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_menu_order_number', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('orders_order_number_key'), ['order_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
