"""adding url_image and created_at in categories

Revision ID: 15e5b64a99a9
Revises: 3ffee1f04433
Create Date: 2025-08-26 22:30:31.590036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e5b64a99a9'
down_revision = '3ffee1f04433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('url_image')

    # ### end Alembic commands ###
