"""adding table hours

Revision ID: 217b4e37c8e4
Revises: 387e7507b1d2
Create Date: 2025-10-16 17:05:25.510750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217b4e37c8e4'
down_revision = '387e7507b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Time(), nullable=True),
    sa.Column('close', sa.Time(), nullable=True),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opening_hours')
    # ### end Alembic commands ###
