"""add image_url to product

Revision ID: 387e7507b1d2
Revises: b3bcdb5077ce
Create Date: 2025-10-11 13:33:27.878322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387e7507b1d2'
down_revision = 'b3bcdb5077ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
