"""changes in user tables, added roles

Revision ID: 50bd7a04d896
Revises: bfdd79f8c96d
Create Date: 2026-02-12 20:56:09.403425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50bd7a04d896'
down_revision = 'bfdd79f8c96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('activated',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('roles')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('activated',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
