"""changes in orders_products

Revision ID: 89d2a4977aa7
Revises: faf111912be1
Create Date: 2025-11-06 21:05:20.476518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d2a4977aa7'
down_revision = 'faf111912be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('order_products_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_products_order_id_fkey'), 'orders', ['order_id'], ['id'])
        batch_op.alter_column('order_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
