"""add slug

Revision ID: 8c1022912b55
Revises: bf26cd9c1eaf
Create Date: 2025-09-06 02:52:45.194771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1022912b55'
down_revision = 'bf26cd9c1eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('slug', sa.String(), nullable=False, server_default='')
        )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
