"""adding user infos in order

Revision ID: e225b70d4bec
Revises: aa7038283087
Create Date: 2025-11-03 21:11:13.783360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e225b70d4bec'
down_revision = 'aa7038283087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('telephone', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('telephone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
