"""feat: adding order_number

Revision ID: faf111912be1
Revises: e225b70d4bec
Create Date: 2025-11-05 11:41:23.342483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf111912be1'
down_revision = 'e225b70d4bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
