"""remove invoice_url

Revision ID: fc36e0a59f7b
Revises: fcb066654aa5
Create Date: 2025-10-27 20:53:10.871780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc36e0a59f7b'
down_revision = 'fcb066654aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value', sa.Numeric(), nullable=False))
        batch_op.drop_column('total')
        batch_op.drop_column('invoice_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total', sa.NUMERIC(), autoincrement=False, nullable=False))
        batch_op.drop_column('total_value')

    # ### end Alembic commands ###
