"""changes

Revision ID: fcb066654aa5
Revises: 217b4e37c8e4
Create Date: 2025-10-27 20:18:15.534542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb066654aa5'
down_revision = '217b4e37c8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'menus', ['menu_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
