"""fix categories

Revision ID: 684afaaa8373
Revises: 15e5b64a99a9
Create Date: 2025-08-29 21:08:38.682697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684afaaa8373'
down_revision = '15e5b64a99a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_menu_category', ['menu_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uix_menu_category', type_='unique')

    # ### end Alembic commands ###
