services:
  web:
    build:
      context: ./../../../
      dockerfile: source/docker/dockerfiles/Dockerfile
    container_name: pizza-web
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - ./../../../source:/app
    env_file:
      - .env
    networks:
      - network-pizza-management-system
  postgres:
    image: postgres:16.3
    container_name: postgres-pizza-management-system
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-pizza-management-system

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-pizza-management-system
    ports:
      - "${PGADMIN_HOST}:${PGADMIN_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - network-pizza-management-system

  redis:
    image: redis:7.2
    container_name: redis-pizza-management-system
    ports:
      - "6381:6379"
    networks:
      - network-pizza-management-system

volumes:
  pgdata:

networks:
  network-pizza-management-system: