services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

    networks:
      - network-pizza-management-system

  web:
    build:
      context: ./../../../
      dockerfile: source/docker/dockerfiles/Dockerfile
    container_name: application-orkestro
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - ./../../../:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - network-pizza-management-system

  postgres:
    image: postgres:16.3
    container_name: postgres-orkestro
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network-pizza-management-system

  postgres_test:
    image: postgres:16.3
    container_name: postgres-tests-orkestro
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: orkestro_test
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    networks:
      - network-pizza-management-system

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-orkestro
    ports:
      - "${PGADMIN_HOST}:${PGADMIN_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - network-pizza-management-system

  redis:
    image: redis:7.2
    container_name: redis-orkestro
    ports:
      - "6381:6379"
    networks:
      - network-pizza-management-system

  evolution:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.0
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - network-pizza-management-system
      - evolution-net
    env_file:
      - .env

volumes:
  pgdata:
  pgdata_test:
  n8n_data:
  evolution_instances:

networks:
  network-pizza-management-system:
  evolution-net: